config/routes.rb
Weshare::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :items
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete' 
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/items',   to: 'items#index',          via: 'get'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  has_attached_file :avatar, :styles => { :large => "720x720", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates :description, presence: true, length: { maximum: 400 }
  validates :user_id, presence: true
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def self.search(search)
	# where(:title, query) -> This would return an exact match of the query
	 where("title like ?", "%#{search}%") 
  end

  def self.per_page
    3
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items, dependent: :destroy

	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  			uniqueness: true
  	has_secure_password

    geocoded_by :address #read the address
    after_validation :geocode #set the lat and long based on address 

  	def User.new_remember_token
	    SecureRandom.urlsafe_base64
	  end

  	def User.hash(token)
  		Digest::SHA1.hexdigest(token.to_s)
  	end

    def feed
      Item.where("user_id = ?", id)
    end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = "Item created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def show
    @item = Item.find(params[:id])
    @user = @item.user
    @hash = Gmaps4rails.build_markers(@user) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end

  def destroy
    @item.destroy
    redirect_to root_url
  end

  def index
    @search = params[:search].capitalize
    if params[:search]
      @items = Item.search(params[:search]).order("created_at DESC").paginate(page: params[:page])
    else
      @items = Item.all.order('created_at DESC')
    end
  end

  private

    def item_params
      params.require(:item).permit(:avatar, :description, :title) #strong parameters
    end

    def correct_user
      @item = current_user.items.find_by(id: params[:id])
      redirect_to root_url if @item.nil?
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
	    user = User.find_by(email: params[:session][:email].downcase)
	    if user && user.authenticate(params[:session][:password])
	      sign_in user
	      redirect_back_or user
	    else
	      flash.now[:danger] = 'Invalid email/password combination'
	      render 'new'
	    end
	end

	def destroy
	    sign_out
	    redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
	  	@item = current_user.items.build
	  	@feed_items = current_user.feed.paginate(page: params[:page])
  	end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page])
    @usersall = User.find(:all)
    @usersloc = []
    @usersall.each_index do |i|
      if !(@usersall[i][:address].nil?)
        @usersloc.push @usersall[i]
      end
    end
    @hash2 = Gmaps4rails.build_markers(@usersloc) do |user, marker|
      if !(user.latitude.nil?)
        marker.lat user.latitude
        marker.lng user.longitude
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items.paginate(page: params[:page])
    @hash = Gmaps4rails.build_markers(@user) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end

  def new
  	@user = User.new
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to WeShare!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :address)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "WeShare"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
	  remember_token = User.new_remember_token
	  cookies.permanent[:remember_token] = remember_token
	  user.update_attribute(:remember_token, User.hash(remember_token))
	  self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
	   user == current_user
	end

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_url, notice: "Please sign in."
		end
	end

	def current_user?(user)
		user == current_user
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end

	def current_user
	   remember_token = User.hash(cookies[:remember_token])
	   @current_user ||= User.find_by(remember_token: remember_token)
	end

	def sign_out
	    current_user.update_attribute(:remember_token,
	                                  User.hash(User.new_remember_token))
	    cookies.delete(:remember_token)
	    self.current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user, options = { size: 50 })
	  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	  size = options[:size]
	  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	  image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end  
end

app/views/items/_item.html.erb
<div class="col-sm-2 col-md-2 col-lg-2 col-centered">
	<li class="single-item">
		<%= image_tag(item.avatar.url(:medium), alt: item.title, class: "item-image img-rounded") %>
	</br>
		<strong><span class="title"><%= item.title %></span></strong>
			<%= link_to "Borrow!", item, class: "btn btn-danger borrow-btn" %>
	</li>

	 <% if current_user?(item.user) %>
    <%= link_to "delete", item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: item.title %>
  	<% end %>

</div>

app/views/items/index.html.erb
<% provide("Search Results") %>
<%-# Insert GMAPS jscript only into the profile page -%>
<% content_for(:header) do %>
<% end %>
<h3>Search Results for <%= "'#{@search}'" %> </h3>
<div class="container">
    <div class="row row-centered">
    	<ol class="items">
          <%= render @items %>
        </ol>
      <%= will_paginate @items%>
    </div>
</div>

app/views/items/show.html.erb
<% provide(:title, @item.title) %>
<%-# Insert GMAPS jscript only into the profile page -%>
<% content_for(:header) do %>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<% end %>

<% if @user.items.any? %>
<div class="item-display">
    <div class="image-container">
      <%= image_tag(@item.avatar.url(:large), alt: @item.title, class: "item-display-image img-rounded") %>
    </div>
</div>

<section class="item-info">
    <h3 class="item-title"><%= @item.title %></h3>
    <ul class="info-list">
    <li class="info-list-item item-description">
      <%= @item.description %>
    </li>
    <li class="info-list-item item-description">
      <%= @item.category %>
    </li>
    <li class="info-list-item">
      Shared by: <%= link_to @user.name, @user, class: "user-name-link" %>
    </li>
    <li class="info-list-item">
    </ul>
    <a href="mailto:<%=@user.email%>" class="btn btn-primary email-button">Send a Request!</a>
</section>

  <% if !(@hash[0][:lat].nil?) && !(@hash[0][:lng].nil?) %>
    <div class="goog-map" style="clear:both">
      <div id="map" style='height: 400px; '></div>
    </div>

    <script type="text/javascript">
 	    handler = Gmaps.build('Google');
      handler.buildMap({ provider : {}, internal: {id: 'map'}}, function(){
		  markers = handler.addMarkers(<%=raw @hash.to_json %>);
		  handler.bounds.extendWith(markers)
		  handler.fitMapToBounds();
      });
    </script>
  <% end %>
</div>

 <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="<%=root_path%>" class="navbar-brand" id="logo"> <%=image_tag("weshare_logo.png") %> </a>
      <%= link_to "weshare", root_path, class: "navbar-brand", id: "logo" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav">
        <li class="search-list-item">
          <%= form_tag(items_path, :method => 'get', class: "navbar-form", role: "search") do %>
            <%= search_field_tag :search, params[:search], class: "form-control" %>
            <%= button_tag "Search", class: "btn btn-default search-button"%>
        <% end%>
        </li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag 'favicon.ico' %>

    <% if content_for?(:header) %><%= yield(:header) %><% end %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" id="error_explanation"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    </div>
  </body>
</html>

app/views/shared/_address_selector.html.erb
<select id="user_address">
	<option value="Hewitt 9">Hewitt 9</option>
	<option value="41 Wyllys Ave">41 Wyllys</option>
</select>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="items">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
		<%= image_tag(feed_item.avatar.url(:medium), alt: feed_item.title, class: "item-image img-rounded") %>
	</br>
		<strong><span class="title"><%= feed_item.title %></span></strong>
		<button type="button" class="btn btn-success borrow-btn">Borrow!</button>

</li>

app/views/shared/_item_form.html.erb
<%= form_for @item, :html => {:role => 'form', :class => 'item-form', :multipart=>true} do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <h3>Add A New Item</h3>
      <div class="form-group">
      <%= f.label "Item Name" %>
      <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label "Picture" %>
      <%= f.file_field :avatar, style: "border: none" %>
  	  </div>

  	  <%= f.submit "Submit Item", class: "btn btn-large btn-danger" %>

<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= link_to current_user.name, current_user, class: "user-info-partial" %>
</h1>
<span>
  <%= pluralize(current_user.items.count, "item") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  WeShare makes it easier for college students to share their stuff. Need a drill for your carpentry project? Have to iron some clothes? Use WeShare to find someone on your campus with the stuff you need, and share your stuff to make peoples' lives easier. Mom always said, "sharing is caring," and WeShare is making it easier than ever to care for your mates. WeShare was developed by <a href="http://connorjustice.com">Connor Justice</a>, <a href="http://eriki.net">Erik Islo</a>, and Catherine Alvarado for the Digital Wesleyan Fellowship. 
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
For help with WeShare, contact <a href="mailto:connorjustice@gmail.com">Connor Justice</a> or look at our <a href="https://github.com/cjustice/weshare">github repo</a>
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="span">
	      <section>
	        <%= render 'shared/user_info' %>
	      </section>
	      <section class="form-section">
	        <%= render 'shared/item_form' %>
	      </section>
	    </aside>
<%#	   <div class="span8 recent-items"> %>
 <%#  //<h3>Recently Added</h3>%>
 <%#     		//<%= render 'shared/feed' %>
 <%#   //	</div>%>
<%#	</div> %>
<% else %>
<div class="center jumbotron">
 <h1><span style="color: #ff0000;">We</span>Share</h1>

  <h2>
    Share stuff with friends
  </h2>

  	<%= link_to "Sign up now!", signup_path, class: "btn btn-danger btn-lg"%>
</div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="container">
    <%= form_for @user, :html => {:role => 'form'} do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
      <%= f.label :name%>
      <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :location %>
      <%= f.text_field :address, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :password_confirmation, "Confirm Password"%>
      <%= f.password_field :password_confirmation, class: "form-control"%>
      </div>

      <%= gravatar_for @user%>
      <a href="http://gravatar.com/emails">Change profile picture</a>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<% content_for(:header) do %>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<% end %>

<h1>Users</h1>

    <div class="goog-map" style='width: 100%;'>
    	<div id="multi_markers" style='height: 400px;'></div>
    </div>

	<script type="text/javascript">
	 	var handler = Gmaps.build('Google');
		handler.buildMap({ 	internal: {id: 'multi_markers'}}, function(){
			markers = handler.addMarkers(<%=raw @hash2.to_json %>);
			handler.bounds.extendWith(markers)
			handler.fitMapToBounds();
		});
	</script>

<%= will_paginate %>

<ul class="users">
  	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class=".col-lg-6 .col-md-offset-3">
    <%= form_for(@user, html: { role: "form" }) do |f|%>
    	<%= render 'shared/error_messages', object: f.object %>

    	<div class="form-group">
	      <%= f.label :name %>
	      <%= f.text_field :name, :class=> "form-control" %>
	    </div>

    	<div class="form-group">
	      <%= f.label :email %>
	      <%= f.text_field :email, :class=> "form-control"  %>
	    </div>

    	<div class="form-group">
	      <%= f.label :address %>
	      <%= f.text_field :address, :class=> "form-control"  %>
	    </div>

    	<div class="form-group">
	      <%= f.label :password %>
	      <%= f.password_field :password, :class=> "form-control"  %>
	    </div>

    	<div class="form-group">
	      <%= f.label :password_confirmation, "Confirmation" %>
	      <%= f.password_field :password_confirmation, :class=> "form-control"  %>
	    </div>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%-# Insert GMAPS jscript only into the profile page -%>
<% content_for(:header) do %>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<% end %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>

<div class="user-stuff">
    <% if @user.items.any? %>
      <h3><%=@user.name.split(' ')[0] + "'s Stuff"%> </h3>
    <div class="container">
      <div class="row row-centered">
        <ol class="items">
          <%= render @items %>
        </ol>
        <%= will_paginate @items%>
      </div>
    </div>
    <% end %>
  </div>
</div>

  <% if !(@hash[0][:lat].nil?) && !(@hash[0][:lng].nil?) %>
    <div class="goog-map">
      <div id="map" style='height: 400px;'></div>
    </div>

    <script type="text/javascript">
 	    handler = Gmaps.build('Google');
      handler.buildMap({ provider : {}, internal: {id: 'map'}}, function(){
		  markers = handler.addMarkers(<%=raw @hash.to_json %>);
		  handler.bounds.extendWith(markers)
		  handler.fitMapToBounds();
      });
    </script>
  <% end %>
</div>